// Hand-authored N5/N4/N3 grammar point list, checked in as a fixed TypeScript
// constant — same precedent as kangxi-radicals.ts (a small, curated, source-
// of-truth list that isn't parsed from any upstream dataset). There is no
// single canonical machine-readable JLPT grammar list with an open license,
// so this is authored directly against standard JLPT grammar references
// (Shin Kanzen Master, Try!, Tobira-adjacent N5-N3 study lists) rather than
// scraped; see DataSource's "hand-authored" entry in data-sources.ts.
//
// `matchPatterns` are regexes run against SENTENCE.characters during
// transform to attach illustrative examples (see transform.ts's grammar
// section). They intentionally favor conjugated/inflected surface forms
// (sentences are natural text, not dictionary citation forms) and are kept
// tight enough not to over-match short, semantically-empty substrings (e.g.
// a bare "は" or "が" would match nearly every sentence and teach nothing).
//
// Ordering: N5 first, then N4, then N3; within a level, roughly by how
// foundational/frequent the pattern is. This ordering feeds level assignment
// in transform.ts (grammar levels are assigned by JLPT band, ~5 per level).
export interface GrammarPoint {
  slug: string;
  pattern: string;
  titleEn: string;
  jlpt: 5 | 4 | 3;
  formation: string;
  matchPatterns: RegExp[];
  relatedSlugs: string[];
}

export const GRAMMAR_POINTS: GrammarPoint[] = [
  // ------------------------------------------------------------------ N5
  {
    slug: "desu",
    pattern: "～です",
    titleEn: "polite copula (is/am/are)",
    jlpt: 5,
    formation: "N/Na + です",
    matchPatterns: [/です[。？!?、]/, /ですか[。？!?]/],
    relatedSlugs: ["da"],
  },
  {
    slug: "da",
    pattern: "～だ",
    titleEn: "plain copula (is/am/are)",
    jlpt: 5,
    formation: "N/Na + だ",
    matchPatterns: [/だ[。！]/],
    relatedSlugs: ["desu"],
  },
  {
    slug: "masu",
    pattern: "～ます",
    titleEn: "polite non-past verb ending",
    jlpt: 5,
    formation: "V-stem + ます",
    matchPatterns: [/ます[。？!?、]/, /ますか[。？!?]/],
    relatedSlugs: ["masen", "mashita"],
  },
  {
    slug: "masen",
    pattern: "～ません",
    titleEn: "polite negative verb ending",
    jlpt: 5,
    formation: "V-stem + ません",
    matchPatterns: [/ません[。？!?、]/],
    relatedSlugs: ["masu"],
  },
  {
    slug: "mashita",
    pattern: "～ました",
    titleEn: "polite past verb ending",
    jlpt: 5,
    formation: "V-stem + ました",
    matchPatterns: [/ました[。？!?、]/],
    relatedSlugs: ["masu"],
  },
  {
    slug: "masendeshita",
    pattern: "～ませんでした",
    titleEn: "polite past negative verb ending",
    jlpt: 5,
    formation: "V-stem + ませんでした",
    matchPatterns: [/ませんでした[。？!?、]/],
    relatedSlugs: ["mashita"],
  },
  {
    slug: "te-form-request",
    pattern: "～てください",
    titleEn: "please do",
    jlpt: 5,
    formation: "V-te + ください",
    matchPatterns: [/てください/],
    relatedSlugs: ["te-form"],
  },
  {
    slug: "te-form",
    pattern: "～て／～で",
    titleEn: "connecting form (and then / because)",
    jlpt: 5,
    formation: "V-te / Adj-te / N-te",
    matchPatterns: [/て、/, /で、/],
    relatedSlugs: ["te-form-request", "te-imasu"],
  },
  {
    slug: "te-imasu",
    pattern: "～ています",
    titleEn: "ongoing action / current state",
    jlpt: 5,
    formation: "V-te + います",
    matchPatterns: [/ています[。？!?、]/, /ていますか/],
    relatedSlugs: ["te-form"],
  },
  {
    slug: "nai-form",
    pattern: "～ない",
    titleEn: "plain negative",
    jlpt: 5,
    formation: "V-nai stem + ない",
    matchPatterns: [/ない[。？!?]/, /ないで/],
    relatedSlugs: ["masen"],
  },
  {
    slug: "nakute-wa-ikenai",
    pattern: "～なくてはいけない",
    titleEn: "must do",
    jlpt: 5,
    formation: "V-nai stem + なくてはいけない",
    matchPatterns: [/なくてはいけません/, /なくてはいけない/],
    relatedSlugs: ["nakereba-narimasen"],
  },
  {
    slug: "tai",
    pattern: "～たい",
    titleEn: "want to do",
    jlpt: 5,
    formation: "V-stem + たい",
    matchPatterns: [/たいです/, /たいと思/],
    relatedSlugs: [],
  },
  {
    slug: "ta-form",
    pattern: "～た",
    titleEn: "plain past",
    jlpt: 5,
    formation: "V-past stem + た",
    matchPatterns: [/[食飲行見聞来き]た[。！]/, /った[。！]/],
    relatedSlugs: ["mashita"],
  },
  {
    slug: "koto-ga-dekiru",
    pattern: "～ことができる",
    titleEn: "can do",
    jlpt: 5,
    formation: "V-dictionary + ことができる",
    matchPatterns: [/ことができます/, /ことができる/, /ことができません/],
    relatedSlugs: [],
  },
  {
    slug: "mae-ni",
    pattern: "～前に",
    titleEn: "before doing",
    jlpt: 5,
    formation: "V-dictionary/N-の + 前に",
    matchPatterns: [/前に/],
    relatedSlugs: ["ato-de"],
  },
  {
    slug: "ato-de",
    pattern: "～後で",
    titleEn: "after doing",
    jlpt: 5,
    formation: "V-past + 後で",
    matchPatterns: [/た後で/, /た後、/],
    relatedSlugs: ["mae-ni"],
  },
  {
    slug: "kara",
    pattern: "～から",
    titleEn: "because / since (reason)",
    jlpt: 5,
    formation: "plain form + から",
    matchPatterns: [/ですから/, /だから/, /ますから/],
    relatedSlugs: ["node"],
  },
  {
    slug: "node",
    pattern: "～ので",
    titleEn: "because / since (softer reason)",
    jlpt: 5,
    formation: "plain form + ので",
    matchPatterns: [/なので/, /ますので/, /いので/],
    relatedSlugs: ["kara"],
  },
  {
    slug: "kedo",
    pattern: "～けど／～が",
    titleEn: "but (contrast)",
    jlpt: 5,
    formation: "plain/polite form + けど・が",
    matchPatterns: [/ですが、/, /ますが、/, /けど、/, /けれど/],
    relatedSlugs: [],
  },
  {
    slug: "toki",
    pattern: "～時",
    titleEn: "when (a time that)",
    jlpt: 5,
    formation: "V/Adj + 時",
    matchPatterns: [/る時/, /た時/, /な時/, /い時/],
    relatedSlugs: [],
  },
  {
    slug: "nagara",
    pattern: "～ながら",
    titleEn: "while doing",
    jlpt: 5,
    formation: "V-stem + ながら",
    matchPatterns: [/ながら/],
    relatedSlugs: [],
  },
  {
    slug: "mashou",
    pattern: "～ましょう",
    titleEn: "let's do",
    jlpt: 5,
    formation: "V-stem + ましょう",
    matchPatterns: [/ましょう[。！]/, /ましょうか/],
    relatedSlugs: ["mashouka"],
  },
  {
    slug: "mashouka",
    pattern: "～ましょうか",
    titleEn: "shall I/we do",
    jlpt: 5,
    formation: "V-stem + ましょうか",
    matchPatterns: [/ましょうか/],
    relatedSlugs: ["mashou"],
  },
  {
    slug: "tsumori",
    pattern: "～つもり",
    titleEn: "intend to do",
    jlpt: 5,
    formation: "V-dictionary + つもり",
    matchPatterns: [/つもりです/, /つもりだ/],
    relatedSlugs: [],
  },
  {
    slug: "deshou",
    pattern: "～でしょう",
    titleEn: "probably (is)",
    jlpt: 5,
    formation: "plain form + でしょう",
    matchPatterns: [/でしょう[。？!?]/, /でしょうか/],
    relatedSlugs: [],
  },
  {
    slug: "houga-ii",
    pattern: "～方がいい",
    titleEn: "had better do",
    jlpt: 5,
    formation: "V-past/nai + 方がいい",
    matchPatterns: [/方がいいです/, /方がいい[。]/],
    relatedSlugs: [],
  },
  {
    slug: "naide-kudasai",
    pattern: "～ないでください",
    titleEn: "please don't do",
    jlpt: 5,
    formation: "V-nai stem + ないでください",
    matchPatterns: [/ないでください/],
    relatedSlugs: ["te-form-request"],
  },
  {
    slug: "sugiru",
    pattern: "～すぎる",
    titleEn: "too much",
    jlpt: 5,
    formation: "V-stem/Adj-stem + すぎる",
    matchPatterns: [/すぎます/, /すぎた/, /すぎる/],
    relatedSlugs: [],
  },
  {
    slug: "yasui-nikui",
    pattern: "～やすい／～にくい",
    titleEn: "easy/hard to do",
    jlpt: 5,
    formation: "V-stem + やすい・にくい",
    matchPatterns: [/やすいです/, /にくいです/, /やすい[。]/, /にくい[。]/],
    relatedSlugs: [],
  },
  {
    slug: "naru",
    pattern: "～くなる／～になる",
    titleEn: "become",
    jlpt: 5,
    formation: "Adj-stem + くなる／Na + になる",
    matchPatterns: [/くなりました/, /になりました/, /くなる[。]/, /になる[。]/],
    relatedSlugs: [],
  },
  {
    slug: "made",
    pattern: "～まで",
    titleEn: "until",
    jlpt: 5,
    formation: "N/V-dictionary + まで",
    matchPatterns: [/まで[に、]/, /まで待/],
    relatedSlugs: [],
  },
  {
    slug: "kara-made",
    pattern: "～から～まで",
    titleEn: "from...to...",
    jlpt: 5,
    formation: "N + から + N + まで",
    matchPatterns: [/から.{1,15}まで/],
    relatedSlugs: ["made"],
  },
  {
    slug: "to-omoimasu",
    pattern: "～と思います",
    titleEn: "I think that",
    jlpt: 5,
    formation: "plain form + と思います",
    matchPatterns: [/と思います/, /と思う/],
    relatedSlugs: [],
  },
  {
    slug: "to-iimasu",
    pattern: "～と言います",
    titleEn: "is called / said to be",
    jlpt: 5,
    formation: "N/quote + と言います",
    matchPatterns: [/と言います/, /と言った/, /と言う/],
    relatedSlugs: [],
  },
  {
    slug: "temo-ii",
    pattern: "～てもいい",
    titleEn: "may do / it's okay to do",
    jlpt: 5,
    formation: "V-te + もいい",
    matchPatterns: [/てもいいです/, /てもいいですか/],
    relatedSlugs: ["te-wa-ikenai-n5"],
  },
  {
    slug: "te-wa-ikenai-n5",
    pattern: "～てはいけない",
    titleEn: "must not do",
    jlpt: 5,
    formation: "V-te + はいけない",
    matchPatterns: [/てはいけません/, /てはいけない/],
    relatedSlugs: ["temo-ii"],
  },
  {
    slug: "deshou-tag-question",
    pattern: "～ね",
    titleEn: "isn't it (confirmation, tight forms)",
    jlpt: 5,
    formation: "plain/polite form + ね",
    matchPatterns: [/ですね[。]/, /ますね[。]/],
    relatedSlugs: [],
  },
  {
    slug: "shika-nai",
    pattern: "～しかない",
    titleEn: "nothing but / only",
    jlpt: 5,
    formation: "N/V-dictionary + しかない",
    matchPatterns: [/しかありません/, /しかない/],
    relatedSlugs: [],
  },
  // ------------------------------------------------------------------ N4
  {
    slug: "ta-koto-ga-aru",
    pattern: "～たことがある",
    titleEn: "have done before",
    jlpt: 4,
    formation: "V-past + ことがある",
    matchPatterns: [/たことがあります/, /たことがある/],
    relatedSlugs: [],
  },
  {
    slug: "nakereba-narimasen",
    pattern: "～なければならない",
    titleEn: "must do",
    jlpt: 4,
    formation: "V-nai stem + なければならない",
    matchPatterns: [/なければなりません/, /なければならない/],
    relatedSlugs: ["nakute-wa-ikenai"],
  },
  {
    slug: "sou-desu-hearsay",
    pattern: "～そうです",
    titleEn: "I hear that (hearsay)",
    jlpt: 4,
    formation: "plain form + そうです",
    matchPatterns: [/だそうです/, /るそうです/, /たそうです/],
    relatedSlugs: ["you-desu"],
  },
  {
    slug: "you-desu",
    pattern: "～ようです",
    titleEn: "it seems that",
    jlpt: 4,
    formation: "plain form + ようです",
    matchPatterns: [/ようです/, /ような気/],
    relatedSlugs: ["sou-desu-hearsay", "rashii"],
  },
  {
    slug: "rashii",
    pattern: "～らしい",
    titleEn: "seems like / apparently",
    jlpt: 4,
    formation: "plain form + らしい",
    matchPatterns: [/らしいです/, /らしい[。]/],
    relatedSlugs: ["you-desu"],
  },
  {
    slug: "kamoshiremasen",
    pattern: "～かもしれません",
    titleEn: "might / maybe",
    jlpt: 4,
    formation: "plain form + かもしれません",
    matchPatterns: [/かもしれません/, /かもしれない/],
    relatedSlugs: [],
  },
  {
    slug: "hazu-da",
    pattern: "～はずだ",
    titleEn: "should be / expected to be",
    jlpt: 4,
    formation: "plain form + はずだ",
    matchPatterns: [/はずです/, /はずだ/, /はずがない/],
    relatedSlugs: [],
  },
  {
    slug: "you-ni-naru",
    pattern: "～ようになる",
    titleEn: "reach the point where / come to do",
    jlpt: 4,
    formation: "V-dictionary + ようになる",
    matchPatterns: [/ようになりました/, /ようになる/],
    relatedSlugs: [],
  },
  {
    slug: "you-ni-suru",
    pattern: "～ようにする",
    titleEn: "make an effort to do",
    jlpt: 4,
    formation: "V-dictionary/nai + ようにする",
    matchPatterns: [/ようにしています/, /ようにします/, /ようにしてください/],
    relatedSlugs: ["you-ni-naru"],
  },
  {
    slug: "tame-ni",
    pattern: "～ために",
    titleEn: "in order to / for the sake of",
    jlpt: 4,
    formation: "V-dictionary/N-の + ために",
    matchPatterns: [/ために/],
    relatedSlugs: [],
  },
  {
    slug: "ba-form",
    pattern: "～ば",
    titleEn: "conditional (if)",
    jlpt: 4,
    formation: "V-ba / Adj-ければ",
    matchPatterns: [/ければ/, /れば[、。]/],
    relatedSlugs: ["tara", "to-conditional"],
  },
  {
    slug: "tara",
    pattern: "～たら",
    titleEn: "conditional (if/when)",
    jlpt: 4,
    formation: "V-past + ら",
    matchPatterns: [/たら[、。？]/, /だったら/],
    relatedSlugs: ["ba-form", "to-conditional"],
  },
  {
    slug: "to-conditional",
    pattern: "～と",
    titleEn: "conditional (whenever / naturally follows)",
    jlpt: 4,
    formation: "plain non-past + と",
    matchPatterns: [/すると、/, /なると、/],
    relatedSlugs: ["ba-form", "tara"],
  },
  {
    slug: "noni",
    pattern: "～のに",
    titleEn: "even though / despite",
    jlpt: 4,
    formation: "plain form + のに",
    matchPatterns: [/のに、/, /のに[。！]/],
    relatedSlugs: [],
  },
  {
    slug: "shi-listing",
    pattern: "～し",
    titleEn: "and (listing reasons)",
    jlpt: 4,
    formation: "plain form + し",
    matchPatterns: [/です[し]、/, /ます[し]、/],
    relatedSlugs: [],
  },
  {
    slug: "sase-form",
    pattern: "～させる",
    titleEn: "causative (make/let someone do)",
    jlpt: 4,
    formation: "V-nai stem + させる",
    matchPatterns: [/させます/, /させました/, /させてください/, /させる[。]/],
    relatedSlugs: ["rareru-passive"],
  },
  {
    slug: "rareru-passive",
    pattern: "～られる／～れる",
    titleEn: "passive (be done to)",
    jlpt: 4,
    formation: "V-nai stem + られる／れる",
    matchPatterns: [/られました/, /られる[。]/, /られています/],
    relatedSlugs: ["sase-form"],
  },
  {
    slug: "sasete-kudasai",
    pattern: "～させてください",
    titleEn: "please let me do",
    jlpt: 4,
    formation: "V-nai stem + させてください",
    matchPatterns: [/させてください/],
    relatedSlugs: ["sase-form"],
  },
  {
    slug: "you-to-omou",
    pattern: "～（よ）うと思う",
    titleEn: "intend to / thinking of doing",
    jlpt: 4,
    formation: "V-volitional + と思う",
    matchPatterns: [/うと思っています/, /ようと思います/, /ようと思う/],
    relatedSlugs: ["tsumori"],
  },
  {
    slug: "aida",
    pattern: "～間",
    titleEn: "while / during the interval",
    jlpt: 4,
    formation: "V-continuous/N-の + 間",
    matchPatterns: [/ている間/, /間に、/, /間は/],
    relatedSlugs: ["aida-ni"],
  },
  {
    slug: "aida-ni",
    pattern: "～間に",
    titleEn: "while (something happens within a span)",
    jlpt: 4,
    formation: "V-continuous/N-の + 間に",
    matchPatterns: [/間に/],
    relatedSlugs: ["aida"],
  },
  {
    slug: "bakari",
    pattern: "～ばかり",
    titleEn: "only / just did",
    jlpt: 4,
    formation: "V-past + ばかり／N + ばかり",
    matchPatterns: [/たばかり/, /ばかりです/],
    relatedSlugs: [],
  },
  {
    slug: "to-wa-kagiranai",
    pattern: "～と（は）限らない",
    titleEn: "not necessarily",
    jlpt: 4,
    formation: "plain form + とは限らない",
    matchPatterns: [/とは限りません/, /とは限らない/],
    relatedSlugs: [],
  },
  {
    slug: "kiri",
    pattern: "～きり",
    titleEn: "only / ever since",
    jlpt: 4,
    formation: "V-past + きり",
    matchPatterns: [/たきり/, /きりです/],
    relatedSlugs: [],
  },
  {
    slug: "ageru-kureru-morau",
    pattern: "～てあげる／～てくれる／～てもらう",
    titleEn: "giving/receiving favors",
    jlpt: 4,
    formation: "V-te + あげる・くれる・もらう",
    matchPatterns: [/てあげます/, /てくれます/, /てもらいます/, /てくれました/, /てもらいました/],
    relatedSlugs: [],
  },
  {
    slug: "temo",
    pattern: "～ても",
    titleEn: "even if / even though",
    jlpt: 4,
    formation: "V-te + も",
    matchPatterns: [/ても、/, /でも、/],
    relatedSlugs: [],
  },
  {
    slug: "toori-ni",
    pattern: "～通りに",
    titleEn: "just as / according to",
    jlpt: 4,
    formation: "V-dictionary/N-の + 通りに",
    matchPatterns: [/通りに/, /通りです/],
    relatedSlugs: [],
  },
  {
    slug: "kata",
    pattern: "～方",
    titleEn: "how to do",
    jlpt: 4,
    formation: "V-stem + 方",
    matchPatterns: [/方が分かりません/, /方を教えて/, /の作り方/, /の使い方/],
    relatedSlugs: [],
  },
  {
    slug: "temo-ii-desu-ka",
    pattern: "～てもいいですか",
    titleEn: "is it okay if I do",
    jlpt: 4,
    formation: "V-te + もいいですか",
    matchPatterns: [/てもいいですか/],
    relatedSlugs: ["temo-ii"],
  },
  {
    slug: "hou-ga",
    pattern: "～より～の方が",
    titleEn: "more...than... (comparison)",
    jlpt: 4,
    formation: "N + より + N + の方が",
    matchPatterns: [/より.{1,10}の方が/],
    relatedSlugs: [],
  },
  {
    slug: "sou-desu-appearance",
    pattern: "～そう（様態）",
    titleEn: "looks like (appearance)",
    jlpt: 4,
    formation: "V-stem/Adj-stem + そう",
    matchPatterns: [/そうな顔/, /そうに見え/, /降りそう/],
    relatedSlugs: ["sou-desu-hearsay"],
  },
  {
    slug: "koto-ni-suru",
    pattern: "～ことにする",
    titleEn: "decide to do",
    jlpt: 4,
    formation: "V-dictionary/nai + ことにする",
    matchPatterns: [/ことにしました/, /ことにします/, /ことにしている/],
    relatedSlugs: ["koto-ni-naru"],
  },
  {
    slug: "koto-ni-naru",
    pattern: "～ことになる",
    titleEn: "it has been decided that",
    jlpt: 4,
    formation: "V-dictionary/nai + ことになる",
    matchPatterns: [/ことになりました/, /ことになっています/, /ことになる[。]/],
    relatedSlugs: ["koto-ni-suru"],
  },
  {
    slug: "n-desu",
    pattern: "～んです",
    titleEn: "explanatory (the thing is...)",
    jlpt: 4,
    formation: "plain form + んです",
    matchPatterns: [/んです[。？!?、]/, /んですか/],
    relatedSlugs: [],
  },
  // ------------------------------------------------------------------ N3
  {
    slug: "wake-da",
    pattern: "～わけだ",
    titleEn: "it means that / no wonder",
    jlpt: 3,
    formation: "plain form + わけだ",
    matchPatterns: [/わけです/, /わけだ[。]/],
    relatedSlugs: ["wake-ni-wa-ikanai"],
  },
  {
    slug: "wake-ni-wa-ikanai",
    pattern: "～わけにはいかない",
    titleEn: "cannot afford to (do)",
    jlpt: 3,
    formation: "V-dictionary + わけにはいかない",
    matchPatterns: [/わけにはいきません/, /わけにはいかない/],
    relatedSlugs: ["wake-da"],
  },
  {
    slug: "beki-da",
    pattern: "～べきだ",
    titleEn: "should do (moral obligation)",
    jlpt: 3,
    formation: "V-dictionary + べきだ",
    matchPatterns: [/べきです/, /べきだ[。]/, /べきではない/],
    relatedSlugs: [],
  },
  {
    slug: "you-toshite",
    pattern: "～（よ）うとする",
    titleEn: "try to / about to do",
    jlpt: 3,
    formation: "V-volitional + とする",
    matchPatterns: [/うとしました/, /ようとしている/, /ようとした時/],
    relatedSlugs: [],
  },
  {
    slug: "totan-ni",
    pattern: "～たとたん（に）",
    titleEn: "the moment that / as soon as",
    jlpt: 3,
    formation: "V-past + とたん（に）",
    matchPatterns: [/たとたんに/, /たとたん、/],
    relatedSlugs: [],
  },
  {
    slug: "nikawari",
    pattern: "～かわりに",
    titleEn: "instead of / in exchange for",
    jlpt: 3,
    formation: "V-dictionary/N-の + かわりに",
    matchPatterns: [/かわりに/],
    relatedSlugs: [],
  },
  {
    slug: "ippou-da",
    pattern: "～一方だ",
    titleEn: "only getting more (continuing trend)",
    jlpt: 3,
    formation: "V-dictionary + 一方だ",
    matchPatterns: [/一方です/, /一方だ[。]/],
    relatedSlugs: [],
  },
  {
    slug: "tsutsu-aru",
    pattern: "～つつある",
    titleEn: "in the process of doing",
    jlpt: 3,
    formation: "V-stem + つつある",
    matchPatterns: [/つつあります/, /つつある[。]/],
    relatedSlugs: [],
  },
  {
    slug: "ni-tsurete",
    pattern: "～につれて",
    titleEn: "as (something changes, so does)",
    jlpt: 3,
    formation: "V-dictionary/N + につれて",
    matchPatterns: [/につれて/],
    relatedSlugs: [],
  },
  {
    slug: "ni-yotte",
    pattern: "～によって",
    titleEn: "depending on / by means of",
    jlpt: 3,
    formation: "N + によって",
    matchPatterns: [/によって/, /により、/],
    relatedSlugs: [],
  },
  {
    slug: "ni-taishite",
    pattern: "～に対して",
    titleEn: "towards / in contrast to",
    jlpt: 3,
    formation: "N + に対して",
    matchPatterns: [/に対して/, /に対する/],
    relatedSlugs: [],
  },
  {
    slug: "ni-kanshite",
    pattern: "～に関して",
    titleEn: "regarding / concerning",
    jlpt: 3,
    formation: "N + に関して",
    matchPatterns: [/に関して/, /に関する/],
    relatedSlugs: [],
  },
  {
    slug: "ue-de",
    pattern: "～上で",
    titleEn: "after doing / in the process of",
    jlpt: 3,
    formation: "V-past/N-の + 上で",
    matchPatterns: [/た上で/, /の上で/],
    relatedSlugs: [],
  },
  {
    slug: "kagiri",
    pattern: "～限り",
    titleEn: "as long as / to the extent that",
    jlpt: 3,
    formation: "plain form + 限り",
    matchPatterns: [/限り、/, /限りは/, /限りでは/],
    relatedSlugs: [],
  },
  {
    slug: "kanenai",
    pattern: "～かねない",
    titleEn: "might well (negative outcome)",
    jlpt: 3,
    formation: "V-stem + かねない",
    matchPatterns: [/かねません/, /かねない[。]/],
    relatedSlugs: [],
  },
  {
    slug: "ni-chigainai",
    pattern: "～に違いない",
    titleEn: "must be / no doubt that",
    jlpt: 3,
    formation: "plain form + に違いない",
    matchPatterns: [/に違いありません/, /に違いない/],
    relatedSlugs: [],
  },
  {
    slug: "gachi",
    pattern: "～がち",
    titleEn: "tends to / prone to",
    jlpt: 3,
    formation: "V-stem/N + がち",
    matchPatterns: [/がちです/, /がちな/, /がちだ[。]/],
    relatedSlugs: [],
  },
  {
    slug: "ppanashi",
    pattern: "～っぱなし",
    titleEn: "left in a state (neglected)",
    jlpt: 3,
    formation: "V-stem + っぱなし",
    matchPatterns: [/っぱなしです/, /っぱなしにして/, /っぱなしだ[。]/],
    relatedSlugs: [],
  },
  {
    slug: "nai-koto-ni-wa",
    pattern: "～ないことには",
    titleEn: "unless (something happens first)",
    jlpt: 3,
    formation: "V-nai + ことには",
    matchPatterns: [/ないことには/],
    relatedSlugs: [],
  },
  {
    slug: "uchi-ni",
    pattern: "～うちに",
    titleEn: "while (still in a state, before change)",
    jlpt: 3,
    formation: "V-continuous/Adj + うちに",
    matchPatterns: [/ないうちに/, /ているうちに/, /うちに帰/],
    relatedSlugs: [],
  },
  {
    slug: "hodo",
    pattern: "～ほど",
    titleEn: "to the extent that / as...as",
    jlpt: 3,
    formation: "V-dictionary/Adj/N + ほど",
    matchPatterns: [/ほど、/, /ほどです/, /ほどの/],
    relatedSlugs: [],
  },
  {
    slug: "sae-ba",
    pattern: "～さえ～ば",
    titleEn: "if only / as long as",
    jlpt: 3,
    formation: "N + さえ + V-ba",
    matchPatterns: [/さえ.{1,10}すれば/, /さえあれば/, /さえいれば/],
    relatedSlugs: ["ba-form"],
  },
  {
    slug: "tatoe-temo",
    pattern: "～たとえ～ても",
    titleEn: "even if (emphatic)",
    jlpt: 3,
    formation: "たとえ + V-te + も",
    matchPatterns: [/たとえ.{1,15}ても/, /たとえ.{1,15}でも/],
    relatedSlugs: ["temo"],
  },
  {
    slug: "seide",
    pattern: "～せいで",
    titleEn: "because of (blame)",
    jlpt: 3,
    formation: "V-past/N-の + せいで",
    matchPatterns: [/せいで/, /せいだ[。]/],
    relatedSlugs: [],
  },
  {
    slug: "okage-de",
    pattern: "～おかげで",
    titleEn: "thanks to",
    jlpt: 3,
    formation: "V-past/N-の + おかげで",
    matchPatterns: [/おかげで/, /おかげだ[。]/],
    relatedSlugs: ["seide"],
  },
  {
    slug: "tokoro-da",
    pattern: "～ところだ",
    titleEn: "just about to / just did / in the middle of",
    jlpt: 3,
    formation: "V-dictionary/past/continuous + ところだ",
    matchPatterns: [/るところです/, /たところです/, /ているところです/],
    relatedSlugs: [],
  },
  {
    slug: "to-ieba",
    pattern: "～と言えば",
    titleEn: "speaking of",
    jlpt: 3,
    formation: "N + と言えば",
    matchPatterns: [/と言えば/, /といえば/],
    relatedSlugs: [],
  },
  {
    slug: "ba-yokatta",
    pattern: "～ばよかった",
    titleEn: "should have done (regret)",
    jlpt: 3,
    formation: "V-ba + よかった",
    matchPatterns: [/ばよかった/, /ければよかった/],
    relatedSlugs: ["ba-form"],
  },
  {
    slug: "mono-da",
    pattern: "～ものだ",
    titleEn: "used to / naturally does (nostalgic/general truth)",
    jlpt: 3,
    formation: "V-past/dictionary + ものだ",
    matchPatterns: [/たものです/, /ものだ[。]/, /ものだった/],
    relatedSlugs: [],
  },
  {
    slug: "kke",
    pattern: "～っけ",
    titleEn: "wasn't it...? (trying to recall)",
    jlpt: 3,
    formation: "plain form + っけ",
    matchPatterns: [/だっけ[。？]/, /たっけ[。？]/],
    relatedSlugs: [],
  },
  {
    slug: "nakya",
    pattern: "～なきゃ",
    titleEn: "have to (casual contraction)",
    jlpt: 3,
    formation: "V-nai stem + なきゃ",
    matchPatterns: [/なきゃ[。！]/, /なきゃいけない/, /なきゃならない/],
    relatedSlugs: ["nakereba-narimasen"],
  },
  {
    slug: "wo-tooshite",
    pattern: "～を通して",
    titleEn: "through / by means of",
    jlpt: 3,
    formation: "N + を通して",
    matchPatterns: [/を通して/, /を通じて/],
    relatedSlugs: [],
  },
  {
    slug: "ni-motozuite",
    pattern: "～に基づいて",
    titleEn: "based on",
    jlpt: 3,
    formation: "N + に基づいて",
    matchPatterns: [/に基づいて/, /に基づく/],
    relatedSlugs: [],
  },
  {
    slug: "ni-kawatte",
    pattern: "～に代わって",
    titleEn: "in place of / on behalf of",
    jlpt: 3,
    formation: "N + に代わって",
    matchPatterns: [/に代わって/, /に代わり、/],
    relatedSlugs: [],
  },
  {
    slug: "ni-sotte",
    pattern: "～に沿って",
    titleEn: "along / in line with",
    jlpt: 3,
    formation: "N + に沿って",
    matchPatterns: [/に沿って/],
    relatedSlugs: [],
  },
];
