// The 214 classical Kangxi radicals: number, canonical character, English
// name, stroke count, and common variant forms (e.g. water 水 has 氵/氺;
// heart 心 has 忄). This is a fixed, small, 300-year-old standard (the
// Kangxi Dictionary, 1716) — the list itself is not copyrightable. Canonical
// characters are drawn from the Unicode Kangxi Radicals block (U+2F00-
// U+2FD5), which assigns exactly one code point per radical number in
// order; English names and variant forms are the conventional glosses used
// by every major kanji dictionary and cross-checked against Kanji Alive's
// language-data/japanese-radicals.csv (CC BY 4.0, data/raw/) for the
// romaji/variant spellings, though that CSV's own row numbering does not
// map 1:1 to Kangxi numbers (see scripts/seed/README.md).
//
// `variants` are alternate glyph forms a KRADFILE component may present as
// (either true Unicode variation, e.g. 氵, or the plain CJK Unified
// Ideograph form KRADFILE sometimes uses in place of the Kangxi Radicals
// block form, e.g. 水 for 06C34 vs the Kangxi block ⽔ U+2F96). Every
// variant resolves back to this radical's canonical `character`.
export interface KangxiRadical {
  number: number;
  character: string;
  name: string;
  romaji: string;
  strokes: number;
  variants: string[];
}

export const KANGXI_RADICALS: KangxiRadical[] = [
  { number: 1, character: "一", name: "one", romaji: "ichi", strokes: 1, variants: [] },
  { number: 2, character: "丨", name: "line", romaji: "tatebou", strokes: 1, variants: [] },
  { number: 3, character: "丶", name: "dot", romaji: "ten", strokes: 1, variants: [] },
  { number: 4, character: "丿", name: "slash", romaji: "no", strokes: 1, variants: [] },
  { number: 5, character: "乙", name: "second", romaji: "otsu", strokes: 1, variants: ["乚"] },
  { number: 6, character: "亅", name: "hook", romaji: "kagi", strokes: 1, variants: [] },
  { number: 7, character: "二", name: "two", romaji: "ni", strokes: 2, variants: [] },
  { number: 8, character: "亠", name: "lid", romaji: "nabebuta", strokes: 2, variants: [] },
  { number: 9, character: "人", name: "person", romaji: "hito", strokes: 2, variants: ["亻", "𠆢"] },
  { number: 10, character: "儿", name: "legs", romaji: "hitoashi", strokes: 2, variants: [] },
  { number: 11, character: "入", name: "enter", romaji: "iru", strokes: 2, variants: [] },
  { number: 12, character: "八", name: "eight", romaji: "hachi", strokes: 2, variants: ["丷"] },
  { number: 13, character: "冂", name: "wide", romaji: "keigamae", strokes: 2, variants: [] },
  { number: 14, character: "冖", name: "cover", romaji: "wakanmuri", strokes: 2, variants: [] },
  { number: 15, character: "冫", name: "ice", romaji: "nisui", strokes: 2, variants: [] },
  { number: 16, character: "几", name: "table", romaji: "tsukue", strokes: 2, variants: [] },
  { number: 17, character: "凵", name: "container", romaji: "kannyou", strokes: 2, variants: [] },
  { number: 18, character: "刀", name: "knife", romaji: "katana", strokes: 2, variants: ["刂"] },
  { number: 19, character: "力", name: "power", romaji: "chikara", strokes: 2, variants: [] },
  { number: 20, character: "勹", name: "wrap", romaji: "tsutsumigamae", strokes: 2, variants: [] },
  { number: 21, character: "匕", name: "spoon", romaji: "saji", strokes: 2, variants: [] },
  { number: 22, character: "匚", name: "box", romaji: "hakogamae", strokes: 2, variants: [] },
  { number: 23, character: "匸", name: "hiding enclosure", romaji: "kakushigamae", strokes: 2, variants: [] },
  { number: 24, character: "十", name: "ten", romaji: "juu", strokes: 2, variants: [] },
  { number: 25, character: "卜", name: "divination", romaji: "boku", strokes: 2, variants: [] },
  { number: 26, character: "卩", name: "seal", romaji: "fushizukuri", strokes: 2, variants: ["㔾"] },
  { number: 27, character: "厂", name: "cliff", romaji: "gandare", strokes: 2, variants: [] },
  { number: 28, character: "厶", name: "private", romaji: "mu", strokes: 2, variants: [] },
  { number: 29, character: "又", name: "again", romaji: "mata", strokes: 2, variants: [] },
  { number: 30, character: "口", name: "mouth", romaji: "kuchi", strokes: 3, variants: [] },
  { number: 31, character: "囗", name: "enclosure", romaji: "kunigamae", strokes: 3, variants: [] },
  { number: 32, character: "土", name: "earth", romaji: "tsuchi", strokes: 3, variants: [] },
  { number: 33, character: "士", name: "scholar", romaji: "samurai", strokes: 3, variants: [] },
  { number: 34, character: "夂", name: "go", romaji: "fuyugashira", strokes: 3, variants: [] },
  { number: 35, character: "夊", name: "go slowly", romaji: "natsuashi", strokes: 3, variants: [] },
  { number: 36, character: "夕", name: "evening", romaji: "yuube", strokes: 3, variants: [] },
  { number: 37, character: "大", name: "big", romaji: "dai", strokes: 3, variants: [] },
  { number: 38, character: "女", name: "woman", romaji: "onna", strokes: 3, variants: [] },
  { number: 39, character: "子", name: "child", romaji: "ko", strokes: 3, variants: [] },
  { number: 40, character: "宀", name: "roof", romaji: "ukanmuri", strokes: 3, variants: [] },
  { number: 41, character: "寸", name: "inch", romaji: "sun", strokes: 3, variants: [] },
  { number: 42, character: "小", name: "small", romaji: "shou", strokes: 3, variants: ["⺌"] },
  { number: 43, character: "尢", name: "lame", romaji: "dainomageashi", strokes: 3, variants: [] },
  { number: 44, character: "尸", name: "corpse", romaji: "shikabane", strokes: 3, variants: [] },
  { number: 45, character: "屮", name: "sprout", romaji: "kusanome", strokes: 3, variants: [] },
  { number: 46, character: "山", name: "mountain", romaji: "yama", strokes: 3, variants: [] },
  { number: 47, character: "巛", name: "river", romaji: "kawa", strokes: 3, variants: ["川"] },
  { number: 48, character: "工", name: "work", romaji: "takumi", strokes: 3, variants: [] },
  { number: 49, character: "己", name: "self", romaji: "onore", strokes: 3, variants: [] },
  { number: 50, character: "巾", name: "cloth", romaji: "haba", strokes: 3, variants: [] },
  { number: 51, character: "干", name: "dry", romaji: "kan", strokes: 3, variants: [] },
  { number: 52, character: "幺", name: "short thread", romaji: "itogashira", strokes: 3, variants: [] },
  { number: 53, character: "广", name: "dotted cliff", romaji: "madare", strokes: 3, variants: [] },
  { number: 54, character: "廴", name: "long stride", romaji: "ennyou", strokes: 3, variants: [] },
  { number: 55, character: "廾", name: "clasped hands", romaji: "nijuuashi", strokes: 3, variants: [] },
  { number: 56, character: "弋", name: "javelin", romaji: "shikigamae", strokes: 3, variants: [] },
  { number: 57, character: "弓", name: "bow", romaji: "yumi", strokes: 3, variants: [] },
  { number: 58, character: "彐", name: "snout", romaji: "keigashira", strokes: 3, variants: ["彑"] },
  { number: 59, character: "彡", name: "bristle", romaji: "sanzukuri", strokes: 3, variants: [] },
  { number: 60, character: "彳", name: "step", romaji: "gyouninben", strokes: 3, variants: [] },
  { number: 61, character: "心", name: "heart", romaji: "kokoro", strokes: 4, variants: ["忄", "㣺"] },
  { number: 62, character: "戈", name: "halberd", romaji: "hoko", strokes: 4, variants: [] },
  { number: 63, character: "戶", name: "door", romaji: "to", strokes: 4, variants: ["戸"] },
  { number: 64, character: "手", name: "hand", romaji: "te", strokes: 4, variants: ["扌"] },
  { number: 65, character: "支", name: "branch", romaji: "shi", strokes: 4, variants: [] },
  { number: 66, character: "攴", name: "rap", romaji: "boku", strokes: 4, variants: ["攵"] },
  { number: 67, character: "文", name: "script", romaji: "bun", strokes: 4, variants: [] },
  { number: 68, character: "斗", name: "dipper", romaji: "to", strokes: 4, variants: [] },
  { number: 69, character: "斤", name: "axe", romaji: "ono", strokes: 4, variants: [] },
  { number: 70, character: "方", name: "square", romaji: "hou", strokes: 4, variants: [] },
  { number: 71, character: "无", name: "not", romaji: "munashii", strokes: 4, variants: [] },
  { number: 72, character: "日", name: "sun", romaji: "hi", strokes: 4, variants: [] },
  { number: 73, character: "曰", name: "say", romaji: "iwaku", strokes: 4, variants: [] },
  { number: 74, character: "月", name: "moon", romaji: "tsuki", strokes: 4, variants: [] },
  { number: 75, character: "木", name: "tree", romaji: "ki", strokes: 4, variants: [] },
  { number: 76, character: "欠", name: "lack", romaji: "kakeru", strokes: 4, variants: [] },
  { number: 77, character: "止", name: "stop", romaji: "tomeru", strokes: 4, variants: [] },
  { number: 78, character: "歹", name: "death", romaji: "gatsuhen", strokes: 4, variants: [] },
  { number: 79, character: "殳", name: "weapon", romaji: "hokozukuri", strokes: 4, variants: [] },
  { number: 80, character: "毋", name: "do not", romaji: "nakare", strokes: 4, variants: [] },
  { number: 81, character: "比", name: "compare", romaji: "kurabu", strokes: 4, variants: [] },
  { number: 82, character: "毛", name: "fur", romaji: "ke", strokes: 4, variants: [] },
  { number: 83, character: "氏", name: "clan", romaji: "uji", strokes: 4, variants: [] },
  { number: 84, character: "气", name: "steam", romaji: "kigamae", strokes: 4, variants: [] },
  { number: 85, character: "水", name: "water", romaji: "mizu", strokes: 4, variants: ["氵", "氺"] },
  { number: 86, character: "火", name: "fire", romaji: "hi", strokes: 4, variants: ["灬"] },
  { number: 87, character: "爪", name: "claw", romaji: "tsume", strokes: 4, variants: ["爫"] },
  { number: 88, character: "父", name: "father", romaji: "chichi", strokes: 4, variants: [] },
  { number: 89, character: "爻", name: "trigrams", romaji: "koumagae", strokes: 4, variants: [] },
  { number: 90, character: "爿", name: "split wood", romaji: "shouhen", strokes: 4, variants: [] },
  { number: 91, character: "片", name: "slice", romaji: "kata", strokes: 4, variants: [] },
  { number: 92, character: "牙", name: "fang", romaji: "kiba", strokes: 4, variants: [] },
  { number: 93, character: "牛", name: "cow", romaji: "ushi", strokes: 4, variants: ["牜"] },
  { number: 94, character: "犬", name: "dog", romaji: "inu", strokes: 4, variants: ["犭"] },
  { number: 95, character: "玄", name: "profound", romaji: "gen", strokes: 5, variants: [] },
  { number: 96, character: "玉", name: "jade", romaji: "tama", strokes: 5, variants: ["王"] },
  { number: 97, character: "瓜", name: "melon", romaji: "uri", strokes: 5, variants: [] },
  { number: 98, character: "瓦", name: "tile", romaji: "kawara", strokes: 5, variants: [] },
  { number: 99, character: "甘", name: "sweet", romaji: "amai", strokes: 5, variants: [] },
  { number: 100, character: "生", name: "life", romaji: "umareru", strokes: 5, variants: [] },
  { number: 101, character: "用", name: "use", romaji: "mochiiru", strokes: 5, variants: [] },
  { number: 102, character: "田", name: "field", romaji: "ta", strokes: 5, variants: [] },
  { number: 103, character: "疋", name: "bolt of cloth", romaji: "hikizukuri", strokes: 5, variants: [] },
  { number: 104, character: "疒", name: "sickness", romaji: "yamaidare", strokes: 5, variants: [] },
  { number: 105, character: "癶", name: "footsteps", romaji: "hatsugashira", strokes: 5, variants: [] },
  { number: 106, character: "白", name: "white", romaji: "shiro", strokes: 5, variants: [] },
  { number: 107, character: "皮", name: "skin", romaji: "kawa", strokes: 5, variants: [] },
  { number: 108, character: "皿", name: "dish", romaji: "sara", strokes: 5, variants: [] },
  { number: 109, character: "目", name: "eye", romaji: "me", strokes: 5, variants: [] },
  { number: 110, character: "矛", name: "spear", romaji: "hoko", strokes: 5, variants: [] },
  { number: 111, character: "矢", name: "arrow", romaji: "ya", strokes: 5, variants: [] },
  { number: 112, character: "石", name: "stone", romaji: "ishi", strokes: 5, variants: [] },
  { number: 113, character: "示", name: "spirit", romaji: "shimesu", strokes: 5, variants: ["礻"] },
  { number: 114, character: "禸", name: "track", romaji: "guunyou", strokes: 5, variants: [] },
  { number: 115, character: "禾", name: "grain", romaji: "nogihen", strokes: 5, variants: [] },
  { number: 116, character: "穴", name: "cave", romaji: "ana", strokes: 5, variants: [] },
  { number: 117, character: "立", name: "stand", romaji: "tatsu", strokes: 5, variants: [] },
  { number: 118, character: "竹", name: "bamboo", romaji: "take", strokes: 6, variants: ["⺮"] },
  { number: 119, character: "米", name: "rice", romaji: "kome", strokes: 6, variants: [] },
  { number: 120, character: "糸", name: "thread", romaji: "ito", strokes: 6, variants: [] },
  { number: 121, character: "缶", name: "jar", romaji: "kanhen", strokes: 6, variants: [] },
  { number: 122, character: "网", name: "net", romaji: "amigashira", strokes: 6, variants: ["罒"] },
  { number: 123, character: "羊", name: "sheep", romaji: "hitsuji", strokes: 6, variants: [] },
  { number: 124, character: "羽", name: "feather", romaji: "hane", strokes: 6, variants: [] },
  { number: 125, character: "老", name: "old", romaji: "oi", strokes: 6, variants: ["耂"] },
  { number: 126, character: "而", name: "and", romaji: "shikoushite", strokes: 6, variants: [] },
  { number: 127, character: "耒", name: "plow", romaji: "raisuki", strokes: 6, variants: [] },
  { number: 128, character: "耳", name: "ear", romaji: "mimi", strokes: 6, variants: [] },
  { number: 129, character: "聿", name: "brush", romaji: "fudezukuri", strokes: 6, variants: [] },
  // Note: 肉 as a left-side component ("nikuzuki") renders identically to
  // radical 74's 月 (moon) — a genuine, unresolvable-by-glyph ambiguity that
  // KRADFILE itself does not disambiguate either. 月 stays mapped only to
  // radical 74 to avoid a variant colliding with another radical's
  // canonical character.
  { number: 130, character: "肉", name: "meat", romaji: "niku", strokes: 6, variants: [] },
  { number: 131, character: "臣", name: "minister", romaji: "shin", strokes: 6, variants: [] },
  { number: 132, character: "自", name: "self", romaji: "mizukara", strokes: 6, variants: [] },
  { number: 133, character: "至", name: "arrive", romaji: "itaru", strokes: 6, variants: [] },
  { number: 134, character: "臼", name: "mortar", romaji: "usu", strokes: 6, variants: [] },
  { number: 135, character: "舌", name: "tongue", romaji: "shita", strokes: 6, variants: [] },
  { number: 136, character: "舛", name: "oppose", romaji: "maiashi", strokes: 6, variants: [] },
  { number: 137, character: "舟", name: "boat", romaji: "fune", strokes: 6, variants: [] },
  { number: 138, character: "艮", name: "stopping", romaji: "kon", strokes: 6, variants: [] },
  { number: 139, character: "色", name: "color", romaji: "iro", strokes: 6, variants: [] },
  { number: 140, character: "艸", name: "grass", romaji: "kusa", strokes: 6, variants: ["艹"] },
  { number: 141, character: "虍", name: "tiger", romaji: "toragashira", strokes: 6, variants: [] },
  { number: 142, character: "虫", name: "insect", romaji: "mushi", strokes: 6, variants: [] },
  { number: 143, character: "血", name: "blood", romaji: "chi", strokes: 6, variants: [] },
  { number: 144, character: "行", name: "walk enclosure", romaji: "gyougamae", strokes: 6, variants: [] },
  { number: 145, character: "衣", name: "clothes", romaji: "koromo", strokes: 6, variants: ["衤"] },
  { number: 146, character: "西", name: "west", romaji: "nishi", strokes: 6, variants: ["覀"] },
  { number: 147, character: "見", name: "see", romaji: "miru", strokes: 7, variants: [] },
  { number: 148, character: "角", name: "horn", romaji: "tsuno", strokes: 7, variants: [] },
  { number: 149, character: "言", name: "speech", romaji: "gen", strokes: 7, variants: ["訁"] },
  { number: 150, character: "谷", name: "valley", romaji: "tani", strokes: 7, variants: [] },
  { number: 151, character: "豆", name: "bean", romaji: "mame", strokes: 7, variants: [] },
  { number: 152, character: "豕", name: "pig", romaji: "buta", strokes: 7, variants: [] },
  { number: 153, character: "豸", name: "badger", romaji: "mujina", strokes: 7, variants: [] },
  { number: 154, character: "貝", name: "shell", romaji: "kai", strokes: 7, variants: [] },
  { number: 155, character: "赤", name: "red", romaji: "aka", strokes: 7, variants: [] },
  { number: 156, character: "走", name: "run", romaji: "hashiru", strokes: 7, variants: [] },
  { number: 157, character: "足", name: "foot", romaji: "ashi", strokes: 7, variants: ["⻊"] },
  { number: 158, character: "身", name: "body", romaji: "mi", strokes: 7, variants: [] },
  { number: 159, character: "車", name: "cart", romaji: "kuruma", strokes: 7, variants: [] },
  { number: 160, character: "辛", name: "bitter", romaji: "karai", strokes: 7, variants: [] },
  { number: 161, character: "辰", name: "morning", romaji: "shin", strokes: 7, variants: [] },
  { number: 162, character: "辵", name: "walk", romaji: "shinnyou", strokes: 7, variants: ["辶"] },
  // Note: 邑's reduced form is also written 阝 (as a right-side "tsukuri"),
  // visually identical to radical 170's left-side "hen" form of 阜. KRADFILE
  // does not distinguish position, so 阝 resolves to 阜 (170) below, the more
  // frequent of the two as a kanji component; 邑 has no separate variant
  // entry here to avoid mapping 阝 to two different radicals.
  { number: 163, character: "邑", name: "city", romaji: "oosato", strokes: 7, variants: [] },
  { number: 164, character: "酉", name: "wine", romaji: "tori", strokes: 7, variants: [] },
  { number: 165, character: "釆", name: "distinguish", romaji: "wakanmuri2", strokes: 7, variants: [] },
  { number: 166, character: "里", name: "village", romaji: "sato", strokes: 7, variants: [] },
  { number: 167, character: "金", name: "gold", romaji: "kane", strokes: 8, variants: ["釒"] },
  { number: 168, character: "長", name: "long", romaji: "nagai", strokes: 8, variants: [] },
  { number: 169, character: "門", name: "gate", romaji: "mon", strokes: 8, variants: [] },
  { number: 170, character: "阜", name: "mound", romaji: "kozato", strokes: 8, variants: ["阝"] },
  { number: 171, character: "隶", name: "slave", romaji: "reizukuri", strokes: 8, variants: [] },
  { number: 172, character: "隹", name: "short-tailed bird", romaji: "furutori", strokes: 8, variants: [] },
  { number: 173, character: "雨", name: "rain", romaji: "ame", strokes: 8, variants: [] },
  { number: 174, character: "青", name: "blue", romaji: "ao", strokes: 8, variants: [] },
  { number: 175, character: "非", name: "wrong", romaji: "hi", strokes: 8, variants: [] },
  { number: 176, character: "面", name: "face", romaji: "men", strokes: 9, variants: [] },
  { number: 177, character: "革", name: "leather", romaji: "kawa", strokes: 9, variants: [] },
  { number: 178, character: "韋", name: "tanned leather", romaji: "namekawa", strokes: 9, variants: [] },
  { number: 179, character: "韭", name: "leek", romaji: "nira", strokes: 9, variants: [] },
  { number: 180, character: "音", name: "sound", romaji: "oto", strokes: 9, variants: [] },
  { number: 181, character: "頁", name: "leaf", romaji: "ogai", strokes: 9, variants: [] },
  { number: 182, character: "風", name: "wind", romaji: "kaze", strokes: 9, variants: [] },
  { number: 183, character: "飛", name: "fly", romaji: "tobu", strokes: 9, variants: [] },
  { number: 184, character: "食", name: "eat", romaji: "shoku", strokes: 9, variants: ["飠"] },
  { number: 185, character: "首", name: "head", romaji: "kubi", strokes: 9, variants: [] },
  { number: 186, character: "香", name: "fragrant", romaji: "kaori", strokes: 9, variants: [] },
  { number: 187, character: "馬", name: "horse", romaji: "uma", strokes: 10, variants: [] },
  { number: 188, character: "骨", name: "bone", romaji: "hone", strokes: 10, variants: [] },
  { number: 189, character: "高", name: "tall", romaji: "takai", strokes: 10, variants: [] },
  { number: 190, character: "髟", name: "long hair", romaji: "kamikanmuri", strokes: 10, variants: [] },
  { number: 191, character: "鬥", name: "fight", romaji: "tatakaigamae", strokes: 10, variants: [] },
  { number: 192, character: "鬯", name: "sacrificial wine", romaji: "chou", strokes: 10, variants: [] },
  { number: 193, character: "鬲", name: "cauldron", romaji: "kanae", strokes: 10, variants: [] },
  { number: 194, character: "鬼", name: "ghost", romaji: "oni", strokes: 10, variants: [] },
  { number: 195, character: "魚", name: "fish", romaji: "uo", strokes: 11, variants: [] },
  { number: 196, character: "鳥", name: "bird", romaji: "tori", strokes: 11, variants: [] },
  { number: 197, character: "鹵", name: "salt", romaji: "shio", strokes: 11, variants: [] },
  { number: 198, character: "鹿", name: "deer", romaji: "shika", strokes: 11, variants: [] },
  { number: 199, character: "麥", name: "wheat", romaji: "mugi", strokes: 11, variants: ["麦"] },
  { number: 200, character: "麻", name: "hemp", romaji: "asa", strokes: 11, variants: [] },
  { number: 201, character: "黃", name: "yellow", romaji: "ki", strokes: 12, variants: ["黄"] },
  { number: 202, character: "黍", name: "millet", romaji: "kibi", strokes: 12, variants: [] },
  { number: 203, character: "黑", name: "black", romaji: "kuro", strokes: 12, variants: ["黒"] },
  { number: 204, character: "黹", name: "embroidery", romaji: "fu", strokes: 12, variants: [] },
  { number: 205, character: "黽", name: "frog", romaji: "ben", strokes: 13, variants: [] },
  { number: 206, character: "鼎", name: "tripod", romaji: "kanae", strokes: 13, variants: [] },
  { number: 207, character: "鼓", name: "drum", romaji: "tsuzumi", strokes: 13, variants: [] },
  { number: 208, character: "鼠", name: "rat", romaji: "nezumi", strokes: 13, variants: [] },
  { number: 209, character: "鼻", name: "nose", romaji: "hana", strokes: 14, variants: [] },
  { number: 210, character: "齊", name: "even", romaji: "sei", strokes: 14, variants: ["斉"] },
  { number: 211, character: "齒", name: "tooth", romaji: "ha", strokes: 15, variants: ["歯"] },
  { number: 212, character: "龍", name: "dragon", romaji: "ryuu", strokes: 16, variants: ["竜"] },
  { number: 213, character: "龜", name: "turtle", romaji: "kame", strokes: 16, variants: ["亀"] },
  { number: 214, character: "龠", name: "flute", romaji: "yaku", strokes: 17, variants: [] },
];
